// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAGWeb.Data;

#nullable disable

namespace SAGWeb.Migrations
{
    [DbContext(typeof(SagrisaDbContext))]
    [Migration("20250529144200_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAGWeb.Models.Cliente", b =>
                {
                    b.Property<int>("CodCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCliente"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Clase")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lprecios")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LPrecios");

                    b.Property<decimal?>("MontoCredito")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("NomCliente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SaldoCredito")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("TotalDeuda")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Tpago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TPago");

                    b.Property<int?>("Vendedor")
                        .HasColumnType("int");

                    b.HasKey("CodCliente")
                        .HasName("PK__Clientes__DF8324D731A31185");

                    b.HasIndex("Vendedor");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SAGWeb.Models.CotizacionDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CodCotizacion")
                        .HasColumnType("int");

                    b.Property<int>("CodProducto")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("IdDetalle")
                        .HasName("PK__Cotizaci__E43646A58B6A4851");

                    b.HasIndex("CodCotizacion");

                    b.HasIndex("CodProducto");

                    b.ToTable("CotizacionDetalle", (string)null);
                });

            modelBuilder.Entity("SAGWeb.Models.Cotizacione", b =>
                {
                    b.Property<int>("CodCotizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCotizacion"));

                    b.Property<int>("CodCliente")
                        .HasColumnType("int");

                    b.Property<int>("CodVendedor")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("PrecioTotal")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("CodCotizacion")
                        .HasName("PK__Cotizaci__79BA079E7BFF028F");

                    b.HasIndex("CodCliente");

                    b.HasIndex("CodVendedor");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("SAGWeb.Models.SagpreciosEnLinea", b =>
                {
                    b.Property<int>("CodProducto")
                        .HasColumnType("int");

                    b.Property<string>("Bodega")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CantDecimales")
                        .HasColumnType("int");

                    b.Property<string>("Clase")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int?>("Existencia")
                        .HasColumnType("int");

                    b.Property<string>("ListaPrecio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomProducto")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Pbase")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<decimal?>("PorcentajeDesc")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("PrecioSinIva")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("PrecioSinIVA");

                    b.Property<decimal?>("PrecioVenta")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("CodProducto")
                        .HasName("PK__SAGPreci__0D06FDF3ACAA8CAE");

                    b.ToTable("SAGPreciosEnLinea", (string)null);
                });

            modelBuilder.Entity("SAGWeb.Models.SagusuariosMovil", b =>
                {
                    b.Property<int>("CodVendedor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodVendedor")
                        .HasName("PK__SAGUsuar__25F4FC1B6412344B");

                    b.ToTable("SAGUsuariosMovil", (string)null);
                });

            modelBuilder.Entity("SAGWeb.Models.Cliente", b =>
                {
                    b.HasOne("SAGWeb.Models.SagusuariosMovil", "VendedorNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("Vendedor")
                        .HasConstraintName("FK__Clientes__Vended__398D8EEE");

                    b.Navigation("VendedorNavigation");
                });

            modelBuilder.Entity("SAGWeb.Models.CotizacionDetalle", b =>
                {
                    b.HasOne("SAGWeb.Models.Cotizacione", "CodCotizacionNavigation")
                        .WithMany("CotizacionDetalles")
                        .HasForeignKey("CodCotizacion")
                        .IsRequired()
                        .HasConstraintName("FK__Cotizacio__CodCo__4BAC3F29");

                    b.HasOne("SAGWeb.Models.SagpreciosEnLinea", "CodProductoNavigation")
                        .WithMany("CotizacionDetalles")
                        .HasForeignKey("CodProducto")
                        .IsRequired()
                        .HasConstraintName("FK__Cotizacio__CodPr__4CA06362");

                    b.Navigation("CodCotizacionNavigation");

                    b.Navigation("CodProductoNavigation");
                });

            modelBuilder.Entity("SAGWeb.Models.Cotizacione", b =>
                {
                    b.HasOne("SAGWeb.Models.Cliente", "CodClienteNavigation")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("CodCliente")
                        .IsRequired()
                        .HasConstraintName("FK__Cotizacio__CodCl__46E78A0C");

                    b.HasOne("SAGWeb.Models.SagusuariosMovil", "CodVendedorNavigation")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("CodVendedor")
                        .IsRequired()
                        .HasConstraintName("FK__Cotizacio__CodVe__47DBAE45");

                    b.Navigation("CodClienteNavigation");

                    b.Navigation("CodVendedorNavigation");
                });

            modelBuilder.Entity("SAGWeb.Models.Cliente", b =>
                {
                    b.Navigation("Cotizaciones");
                });

            modelBuilder.Entity("SAGWeb.Models.Cotizacione", b =>
                {
                    b.Navigation("CotizacionDetalles");
                });

            modelBuilder.Entity("SAGWeb.Models.SagpreciosEnLinea", b =>
                {
                    b.Navigation("CotizacionDetalles");
                });

            modelBuilder.Entity("SAGWeb.Models.SagusuariosMovil", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Cotizaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
